// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
      "index": 1,
      "add_year" : "2020",
      "title" : "d払いリニューアル ネット&街",
      "kinds" : "ページリニューアル",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/app/shop/",
      "page_url_02" : "",
      "info_01" : "<li>1. Objectデータを利用し、約800個の加盟店のロゴデータを保存</li><li>2. JSONデータを利用し、カテゴライズ</li><li>3. あるデータの中で順番をランダム表示</li><li>4. 運用中サイトのため、運用時の更新等、様々な注意点や効率化を考慮しMTGに参加、結果を反映するような構築を実施 (HTMLだったデータをjsonに変更)</li><li>5. 大量のロゴデータのためlazyload実装</li>",
      "info_02" : "",
      "pc_img": [],
      "sp_img": ['town_dLogo.jpg', 'net_dLogo.jpg'] ,
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_dRe.jpg",
  },
  {
      "index": 2,
      "add_year" : "2021",
      "title" : "終了キャンペーン一覧ページ改修",
      "kinds" : "PAGE改修",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/stg/closed",
      "page_url_02" : "",
      "info_01" : "<li>1. APIのURLパラメーターでデータを獲得</li><li>2. ボタンによるカテゴライズ（画像4個「総6個」）</li><li>3. 該当するデータがない時、カテゴリボタン非表示</li><li>4. データ数20個制限、「もっと見る」ボタンによって20個づつ追加</li><li>5. エントリ済みのフラグによるカテゴリフィルタボタン追加</li><li>5. エントリ済みのフラグによるカテゴリフィルタボタン追加</li><li>6. AJAX通信を使用し、イベント（クリック、画像読み込み）によるAPI集計実装</li>",
      "info_02" : "",
      "pc_img": ['pc_dEndCmp.png'],
      "sp_img": ['sp_dEndCmp.png'],
      "tech" : ["html", "css", "javascript", "AJAX"],
      "titleImg" : "list_dCmp.jpg", 
      
  },
  {
      "index": 3,
      "add_year" : "2021",
      "title" : "キャンペーン一覧ページ改修",
      "kinds" : "PAGE改修",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/",
      "page_url_02" : "",
      "info_01" : "<li>1. エントリ済みのフラグによるカテゴリフィルタ追加</li><li>2. AJAX通信を使用し、イベント（クリック、画像読み込み）によるAPI集計実装</li>",
      "info_02" : "",
      "pc_img": ['pc_dCmp.png'],
      "sp_img": ['sp_dCmp.png'],
      "tech" : ["html", "css", "javascript", "AJAX"],
      "titleImg" : "list_dCmp.jpg", 
      
  },
  {
      "index": 4,
      "add_year" : "2020",
      "title" : "金ビジ フィナンシャルプランナー紹介サービス",
      "kinds" : "LP制作",
      "page_url" : "",
      "page_url_02" : "",
      "info_01" : "<li>1. レスポンシブによるスライダーつき</li><li>2. ボタンによるパラメータ出しわけ</li>",
      "info_02" : "",
      "pc_img": ['pc_dKin.jpg'],
      "sp_img": ['sp_dKin.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_dKin.jpg",
  },
  {
      "index": 5,
      "add_year" : "2020",
      "title" : "【マスターズドリーム】山崎原酒樽熟成ブレンドページ改修",
      "kinds" : "PAGE改修",
      "page_url" : "https://www.suntory.co.jp/beer/pre-mal/mastersdream/yamazaki/blend/index.html",
      "page_url_02" : "https://mobile.suntory.co.jp/beer/pre-mal/mastersdream/yamazaki/blend/index.html",
      "info_01" : "<li>1. PC/SP 適応系li><li>2. スクロールによるコンテンツFADE IN AND OUT</li><li>３. PCページでSPへリダイレクト、SP同様</li><li>４. スライダーライブラリを使用し、イメージページネーション</li>",
      "info_02" : "",
      "pc_img": ['pc_masterDream.jpg'],
      "sp_img": ['sp_masterDream.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_masterDream.jpg", 
  },
  {
      "index": 6,
      "add_year" : "2020",
      "title" : "日本健康管理協会",
      "kinds" : "コンテンツ追加",
      "page_url" : "http://nikkenkyo.or.jp/shinjuku/",
      "page_url_02" : "",
      "info_01" : "<li>1. COOKIEデータを使用し、ポップアップを一日みない機能を開発</li>",
      "info_02" : "",
      "pc_img": ['pc_shinjuku.jpg'],
      "sp_img": [],
      "tech" : ["javascript"],
      "titleImg" : "list_shinjuku.jpg", 
  },
  {
      "index": 7,
      "add_year" : "2020",
      "title" : "【SPS】イントラサイト改修およびエクストラサイト制作",
      "kinds" : "PAGE制作",
      "page_url" : "",
      "page_url_02" : "https://mobile.suntory.co.jp/beer/pre-mal/mastersdream/yamazaki/blend/index.html",
      "info_01" : "<li>1. COOKIEデータを使用し、ポップアップを一日みない機能を開発</li>",
      "info_02" : "",
      "pc_img": ['pc_sps.png'],
      "sp_img": [],
      "tech" : ["javascript"],
      "titleImg" : "list_sps.jpg", 
  },
  {
      "index":8,
      "add_year" : "2021",
      "title" : "請求書リクエスト 受付フォーム",
      "kinds" : "PAGE制作",
      "page_url" : "",
      "page_url_02" : "",
      "info_01" : "<li>1. ３段回select box</li><li>2. FORM入力による有効性検査</li>",
      "info_02" : "",
      "pc_img": ['pc_dRequest.png'],
      "sp_img": ['sp_dRequest.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_dRequest.jpg", 
  },
  {
      "index": 9,
      "add_year" : "2021",
      "title" : "全日食CP",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/dpay_znsp/2103/cpn_20.html",
      "page_url_02" : "",
      "info_01" : "<li>1. select box選択による動作実装</li><li>2. 大量の地域データをJSONで保存し使用</li>",
      "info_02" : "",
      "pc_img": ['pc_zensyoku.png'],
      "sp_img": ['sp_zensyoku.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_zensyoku_pc.jpg", 
  },
  {
      "index": 10,
      "add_year" : "2021",
      "title" : "「プリンツ ベア」ブランドサイトRN",
      "kinds" : "ページ制作",
      "page_url" : "https://duskinduet.digitalmarketing.jp/ohbo/air_cp03.html",
      "page_url_02" : "",
      "info_01" : "<li>1. レスポンシブ</li><li>2. スクロールによるアニメーション実装</li><li>3. 追従メーニュ</li>",
      "info_02" : "",
      "pc_img": ['pc_prinzbear.png'],
      "sp_img": ['sp_prinzbear.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_prinzbear.jpg",
  },
  {
      "index": 11,
      "add_year" : "2021",
      "title" : "【スポ振】セゾンページ制作",
      "kinds" : "ページ制作",
      "page_url" : "",
      "page_url_02" : "",
      "info_01" : "<li>1. ページ内に実装されている</li>",
      "info_02" : "",
      "pc_img": ['pc_sposhin.jpg'],
      "sp_img": [],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_sposhin.jpg",
  },
  {
      "index": 12,
      "add_year" : "2021",
      "title" : "dポイント山分けCP",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/dpay_yamawake/2106/",
      "page_url_02" : "",
      "info_01" : "<li>1. レスポンシブ</li><li>2. タブが入っているSLIDE2つ</li><li>3. YOUTUBE動画をIFRAMEにおさえる</li>",
      "info_02" : "",
      "pc_img": ['pc_yamawake.png'],
      "sp_img": ['sp_yamawake.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_yamawake.jpg",
  },
  {
      "index": 13,
      "add_year" : "2021",
      "title" : "とくトクd払い20％還元CP",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/dpay_tokutoku/2102/cpn_20.html",
      "page_url_02" : "",
      "info_01" : "<li>1. アコディアンボタン</li><li>2. LP共通のINCLUDE化</li>",
      "info_02" : "",
      "pc_img": ['pc_tokutoku.png'],
      "sp_img": ['sp_tokutoku.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_tokutoku.jpg", 
  },
  {
      "index": 14,
      "add_year" : "2021",
      "title" : "HOYA 7月CP(半額 & 30%OFF)",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/dpay_tokutoku/2102/cpn_20.html",
      "page_url_02" : "",
      "info_01" : "<li>1. PC、SP別</li><li>2. 画像中心ページ</li>",
      "info_02" : "",
      "pc_img": ['pc_hoyaHalf.png', 'pc_hoya30.png'],
      "sp_img": ['sp_hoyaHalf.png', 'sp_hoya30.png'],
      "tech" : ["html", "css"],
      "titleImg" : "list_hoyaHalf.png", 
  },
  {
      "index": 15,
      "add_year" : "2020",
      "title" : "【KBI】調理機器カタログ対応（2020秋）_調理機器 ",
      "kinds" : "ページ制作",
      "page_url" : "https://home.osakagas.co.jp/search_buy/gascooker/merit/merit05.html",
      "page_url_02" : "https://home.osakagas.co.jp/sp/search_buy/gascooker/merit/merit05.html",
      "info_01" : "<li>1. PC、SP別</li><li>2. PC,MOBILEに合わせたそれぞれのhtml、cssを実装</li><li>3. Gitを使用し、ファイルのバージョン管理</li>",
      "info_02" : "",
      "pc_img": ['pc_kbi.jpg'],
      "sp_img": ['sp_kbi.png'],
      "tech" : ["html", "css", "git"],
      "titleImg" : "list_kbi.jpg", 
  },
  {
      "index": 16,
      "add_year" : "2021",
      "title" : "ｄ払いデビュー＆おかえりキャンペーン",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/dpay_sb/cpn_dpay_sb.html",
      "page_url_02" : "",
      "info_01" : "<li>1. SWIPERライブラリ使用</li><li>2. レスポンシブページ制作</li><li>３. スライダーバグ解決（TABManuの中入っているとバグ発生）</li>",
      "info_02" : "",
      "pc_img": ['pc_debut.png'],
      "sp_img": ['sp_debut.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_debut.jpg", 
  },
  {
      "index": 17,
      "add_year" : "2021",
      "title" : "dフォト_注文キャンペーン_コーディング",
      "kinds" : "LP制作",
      "page_url" : "",
      "page_url_02" : "",
      "info_01" : "<li>1. レスポンシブ</li><li>2. 前回のソースをより見やすく作成（一部）</li>",
      "info_02" : "",
      "pc_img": ['pc_dfort.png'],
      "sp_img": ['sp_dfort.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_dfort.jpg",
  },
  {
      "index": 18,
      "add_year" : "2021",
      "title" : "duskin SYNERGY & 応募ページ",
      "kinds" : "LP制作",
      "page_url" : "",
      "page_url_02" : "",
      "info_01" : "<li>1. アコディアンボタン</li><li>2. CMS前の段階のHTML、CSS作成</li>",
      "info_02" : "",
      "pc_img": ['pc_duskinSynergy.png', 'pc_duskinEnter.png'],
      "sp_img": ['sp_duskinSynergy.png', 'sp_duskinEnter.png'],
      "tech" : ["html", "css"],
      "titleImg" : "list_duskinSynergy.jpg",
  },
  {
      "index": 19,
      "add_year" : "2020",
      "title" : "d払い(eKYCヘルプサイト新規制作)",
      "kinds" : "ページ制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/guide/app_ekyc_auth.html",
      "page_url_02" : "",
      "info_01" : "<li>1. Javascriptを使用、各カテゴリキーワードに合わせて出てくるコンテンツを作成</li><li>2. カテゴライズに合わせるHTMLを作成</li><li>2. CSS メディアクエリを利用しデバイスによって変化するレスポンシブページを作成</li>",
      "info_02" : "",
      "pc_img": ['pc_ekyc.jpg'],
      "sp_img": ['sp_ekyc.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_ekyc.jpg",
  },
  {
      "index": 20,
      "add_year" : "2021",
      "title" : "【GROWING】SP版のフォント拡大対応",
      "kinds" : "CSS修正",
      "page_url" : "",
      "page_url_02" : "",
      "info_01" : "<li>1. 既存のページに影響されないようCSSを作成</li><li>2. 新規スマートフォンのCSS作成</li>",
      "info_02" : "",
      "pc_img": [],
      "sp_img": ['sp_growing.png'],
      "tech" : [ "css"],
      "titleImg" : "list_growing.jpg",
  },
  {
      "index": 21,
      "add_year" : "2020",
      "title" : "d払い(ローソン d払い+20%還元キャンペーン（d払い配下LP）",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/corporation/shop.html",
      "page_url_02" : "",
      "info_01" : "<li>1. css メディアクエリを利用しデバイスによって変化するレスポンシブページを作成</li><li>2. PC,MOBILEのレイアウトの変化をcssで実装</li>",
      "info_02" : "",
      "pc_img": ['pc_lawson.png'],
      "sp_img": ['sp_lawson.png'],
      "tech" : ["html", "css"],
      "titleImg" : "list_lawson.jpg",
  },
  {
      "index": 22,
      "add_year" : "2020",
      "title" : "docomo(mydaiz_新感覚ナビキャンペーン)",
      "kinds" : "LP制作",
      "page_url" : "",
      "page_url_02" : "",
      "info_01" : "<li>1. youtubeAPIの機能を使用し、動画が終わったらボタンがActiveになる動きを実装</li><li>2. スライダーライブラリ(slick)を実装</li><li>3. css メディアクエリを利用しデバイスによって変化するレスポンシブページを作成</li>",
      "info_02" : "",
      "pc_img": ['pc_myDaiz.jpg'],
      "sp_img": ['sp_myDaiz.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_myDaiz.jpg",
  },
  {
      "index": 23,
      "add_year" : "2021",
      "title" : "d払いをはじめよう！＋50％還元キャンペーン",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/dpay_sb/cpn_dpay_sb.html",
      "page_url_02" : "",
      "info_01" : "<li>1. レスポンシブ</li><li>2. タブが入っているSLIDE2つ</li><li>3. アコーディオンメニュー</li>",
      "info_02" : "",
      "pc_img": ['pc_okaeri.png'],
      "sp_img": ['sp_okaeri.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_okaeri.jpg",
  },
  {
      "index": 24,
      "add_year" : "2021",
      "title" : "【ピジョン株式会社】商品一覧 & 詳細ページのテンプレート改修",
      "kinds" : "ページ修正",
      "page_url" : "https://shop.pigeon.co.jp/category/SEARCH103/",
      "page_url_02" : "",
      "info_01" : "<li>1. ナビゲーションのところをアコーディオンメニューへ修正</li><li>2. 商品検索エリアを修正</li><li>3. 商品詳細ページのレイアウト修正</li>",
      "info_02" : "",
      "pc_img": ['pc_pigeonShop.png', 'pc_pigeonItem.png'],
      "sp_img": ['sp_pigeonShop.png', 'sp_pigeonItem.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_pigeonShop.jpg",
  },
  {
      "index": 25,
      "add_year" : "2020",
      "title" : "SST(CMG（チェンバーミュージック・ガーデン）2020年英語版　ページ修正)",
      "kinds" : "ページ修正",
      "page_url" : "https://www.suntory.com/culture-sports/suntoryhall/feature/chamber2020/index.html",
      "page_url_02" : "",
      "info_01" : "<li>1. ２段回レスポンシブ</li><li>2. リリス前のページ修正</li>",
      "info_02" : "",
      "pc_img": ['pc_sstEng.jpg'],
      "sp_img": ['sp_sstEng.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_sstEng.jpg",
  },
  {
      "index": 26,
      "add_year" : "2020",
      "title" : "d払いクーポンキャンペーン",
      "kinds" : "LP制作",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/campaign/dpay_coupon/index.html",
      "info_01" : "<li>1. レスポンシブ</li><li>2. アコディアンメニュー</li>",
      "info_02" : "",
      "pc_img": ['pc_coupon.png'],
      "sp_img": ['sp_coupon.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_coupon.png",
  },
  {
      "index": 27,
      "add_year" : "2020",
      "title" : "d払いサイト 運用",
      "kinds" : "ページ運用",
      "page_url" : "https://service.smt.docomo.ne.jp/keitai_payment/",
      "info_01" : "<li>1. リアルタイムで更新をするページの運用</li><li>2. サイトの運用管理による数あるページ管理及び更新</li><li>3. サコンポーネントページの作成、テスト環境検証、商用環境へアップデートまでのプロセスを全部経験</li><li>4. ページ運用管理による様々な注意点を習得</li>",
      "info_02" : "",
      "pc_img": ['pc_dBarai.png'],
      "sp_img": ['sp_dBarai.png'],
      "tech" : ["html", "css", "javascript"],
      "titleImg" : "list_dBarai.jpg",
  },
]